### ISSUE TITLE
[Feature Request] Dynamic naming

### ISSUE THREAD

**Issue by matthew-dean** [theKashey/storybook-include#3]
This is a great add-on for monorepos w/ decorators per package. However, it would also be great to be able to use this include strategy to dynamically change the title of components per package. e.g. rewrite:
```ts
export default {
  title: 'Alert'
}
```
to:
```ts
export default {
  title: 'Foo/Alert'
}
```
...based on the storybook-include settings.

**Comment by matthew-dean** [comment]
Oh, I noticed that in Storybook Add-ons, this is listed as `Folder based storybook configuration`.

Does that mean there's a way to configure Storybook fields like `stories`? Stories has a `titlePrefix` property there, for example. https://storybook.js.org/docs/react/configure/overview#with-a-configuration-object

**Comment by theKashey** [comment]
This is not something this plugin could do. I personally use https://github.com/atlassian-labs/babel-plugin-storybook-csf-title and it can prepend package name to a storyname with no time.

**Comment by matthew-dean** [comment]
Yeah, I was able to do this with `titlePrefix` at the root, so it works okay. Thanks!
